class_name Enums

enum CardCategory { NODE, ITEM_RAW, ITEM_PROCESSED, ITEM_FOOD, TOOL, BUILDING, UNIT, PACKAGE, EVENT, CURRENCY_LOOT }
enum Rarity { COMMON, UNCOMMON, RARE, EPIC }
enum ItemType { RAW, PROCESSED, FOOD }
enum UnitRole { ANY = -1, GENERALIST, ENGINEER, SCIENTIST, PILOT, ROBOT_DRONE }
enum UnitState { IDLE, WORKING, TRAVELING, DEAD }
enum ToolEffect { UNLOCK_GATHER, SPEED_BOOST, REPAIR, CRAFT_UNLOCK, REVEAL }
enum EventEffect { DAMAGE_HULL, DAMAGE_O2, STEAL_RESOURCE, POWER_DEBUFF, BUFF_LOOT, PLAYER_CHOICE }
enum BoardZone { SHIP_INTERIOR, OPEN_SPACE }